### ISSUE TITLE
Might be a problem with Batch Sizes

### ISSUE THREAD

**Issue by usmcamp0811** [ludovicdmt/gpu_gmm#2]
I just tried to run the GMM on an 8M record data set and am running out of memory on my GPU. It shows  the `OOM` error for line `182`. The tensor shape it is trying to run a `MatMul` operation for is `[500, 8137747, 1]`. My batches are suppose to be of a size of `256`, so shouldn't this be a tensor of shape `[500, 256, 1]`? 

I dunno I am going to work through this and see if I can fix it.. Just wanted to create the issue in case I broke something with my update to TF2.0.

**Comment by ludovicdmt** [comment]
Could you please be more specific ? Line `182` is calling `E_step` and it would be useful to know at which multiplication in `E_step` is problematic ?
 Could you provide a reproducible test case that is the bare minimum necessary to generate the problem ?

Are your data in dimension 500 ?

**Comment by usmcamp0811** [comment]
Sorry.. I'm doing the work on an offline machine and so I'm switching back and forth between machines...  yea it is in `E_step` its the first line of `E_step`. I think the problem is that I'm initializing `self.input` as the full dataset and then Tensorflow doesn't want to resize it... maybe.. 

Yes I am doing 500 components, the data dimensions is only a 1D. 

I am going back through and removing `self.input` and just passing `batch` into all the functions to see if this fixes things. 

When I get home or solve this I'll post up more complete code.

**Comment by ludovicdmt** [comment]
I'm not using this code anymore so didn't test your modifications before accepting PR, just had a quick look at the code but yes your `self.input=data{ (line 216) is after the `E_step` line 214 so `self.input` is still full dataset...

Beside that, in TF 1.0 I was doing typecasting to be sure that every Variable are tf.float32 (in order to: 1. reduce memory usage compared to tf.float64 and 2. avoiding Error with tf.substract and tf.matmul because of different Variable types). It seems that you removed all this so I now have errors when running test.py... 

I will have a deeper look this week if I have time.

**Comment by ludovicdmt** [comment]
On another note, I don't know much about range/variability of your data but 500 components is REALLY huge even more in 1D...

You could also consider sub-sampling your 8M samples to speed-up computation.

**Comment by usmcamp0811** [comment]
Thanks.. Yea my data is extremely noisy and I am using the GMM essentially to discretize my data so I can use FPGrowth to find frequent patterns. 500 components has objectively worked best so far for my task.. but I'm running into some scaling issues as a lot of my datasets run into the 10-20M record length and even with a beast of a server I have it takes too long to process. I've got a couple of V100s that I want to let loose on the data as I'm able to train in 2 minute vs 20 minutes on a 192 cpu cores.. 

So I've dug around and have things running but hvae found that `gamma_sum` goes to zero and is causing my likelihoods to go to `nan`. I must have mucked something up along the way and am now trying to figure out what

**Comment by usmcamp0811** [comment]
So I figured out the batch problem.. I just had to move line 191 `train_step = self.training_step()` to line 197. 

But in doing all this and all my exploration of things yesterday, I found that there seems to be something wrong with the algorithm itself. Which is crazy because everything works just fine with the `make_blobs` data. What I found was that there is a problem with the `M_step` adding `nan` values to the `means` matrix. This is caused by `gamma_sum` going to `nan` due to a precision error with `exp_log_shifted`. For my data I get the following. 

```
(tf_gmm.log_weighted - tf_gmm.log_shift).numpy().min() == -1824751.0 # if I scale my data prior
(tf_gmm.log_weighted - tf_gmm.log_shift).numpy().min() == -302552.22 # if I don't scale my data
```

So when we take `tf.exp` of values in that range we get `0` due to rounding errors. The actual value being something `<1e-64`. Then when we calculate `gamma` we end up with some `nan` values due to the whole `0/X` thing. And from here everything goes down hill... 

I am able to get my model to converge sometimes, but it seems that it is likely dependent on the initialization step. I've tried all sorts of different component values and batch sizes. None of them seem to really make a difference. I've even upped the sklearn model size and iterations.

**Comment by ludovicdmt** [comment]
Still on `line  214` you are selecting new batch: `self.input = batch[idx]` after computing `E_step` which does not make sense... You should calculate Expectation for the batch at the current step, not previous one. And I noticed that when converting to TF2.0 you removed the computation of  Maximization step, so parameters are never updated during iterations ? You need the `M_step` at some point in the training loop.

`gamma` are the `responsibilities` which are probabilities for each batch samples to belong to each Gaussian (i.e. component) in the mixture. As you are using `500` components some responsibilities are really really low (especially with "bad" init) and end up `nan`. It is not really surprising and not a problem of the algorithm but rather of the hyper-parameters selection. 
Sklearn handles these overflows by rounding them in `float64` range. I did not implement such controls.
